io.pedestal.http.jetty: use SslContextFactory$Server
Using plain org.eclipse.jetty.util.ssl.SslContextFactory fails
with newer Jetty versions when a certificate contains multiple SAN
with wildcard certificates:

java.lang.IllegalStateException: KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory. (Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)

Therefore, use the SslContextFactory$Server instead, after all, Jetty is
being used as a HTTPS server.